apiVersion: apps/v1
kind: Deployment
metadata:
  name: brent-deployment
  labels:
    app: brentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brentapp
  template:
    metadata:
      labels:
        app: brentapp
    spec:
      containers:
      - name: my-container
        image: bmrob123/myapp33:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: brentapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: brentapp 
