#Workflow to build the environement
name: ci
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository on ubuntu runner
        uses: actions/checkout@v4
      - name: Install Java version 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Maven
        run: 
          mvn package
          ls -l
          
      
